[package]
name = "wcm"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.0"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
image = "0.24"
